
spring: 
   application: 
      name: gateway
   cloud:
      gateway:
        routes:
          - id: POST-CLIENT
            uri: lb://POST-CLIENT
            predicates:
             - Path=/posts/**
            filters:
             - name: JwtAuthenticationFilter2
        
          - id: LOGIN-CLIENT
            uri: lb://LOGIN-CLIENT
            predicates:
              - Path=/user/**    
          
         
server: 
    port: 5555
    
    

eureka: 
    
    client: 
      service-url:
          fetchRegistry: true
          preferIpAddress: true
          registerWithEureka: true
          defaultZone: http://13.125.152.144:8761/eureka/
               
jwt:
  secret: ENC(nugQJ8BkKGjd6l6OruPwT7cpYiaQgfYzhYBaMPXPihg=)
